# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title faster linear regression with RcppArmadillo
NULL

#' Below is a simple example of exporting a C++ function to R. You can
#' source this function into an R session using the Rcpp::sourceCpp
#' function or via the Source button on the editor toolbar
NULL

#' For more on using Rcpp click the Help button on the editor toolbar
#' @name fast_lm
#' @param x A single integer.
#' @export fast_lm
NULL

fast_lm <- function(X, y) {
    .Call(`_blblm_fast_lm`, X, y)
}

